# Generated by Django 5.0.2 on 2024-04-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_model',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo_model',
            name='task_name',
            field=models.CharField(max_length=255),
        ),
    ]
