# Generated by Django 5.0.2 on 2024-04-06 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0002_todo_model_task_status_alter_todo_model_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_model',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
